language: java

dist: trusty
sudo: required

addons:
  apt:
    packages:
      - lynx

jdk:
  - openjdk11
  
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

after_failure:
  - if [ -f /home/travis/build/aalaniz18/bridge_crane_model2020/build/reports/tests/test/index.html ]; then lynx -dump /home/travis/build/aalaniz18/bridge_crane_model2020/gradle/wrapper/index.html; fi